import * as LucideIcons from "lucide-react-native";

export interface Achievement {
  id: number;
  cat: "Battle" | "Treasury" | "Career" | "Daily" | "Special";
  title: string;
  iconName: keyof typeof LucideIcons;
  desc: string;
  goal: number;
  statKey?: string;
  rarity: "Common" | "Rare" | "Epic" | "Legendary";
}

export const ACHIEVEMENT_DATA: Achievement[] = [
  // --- BATTLE ---
  {
    id: 1,
    cat: "Battle",
    title: "First Blood",
    iconName: "Droplets",
    desc: "Win your first game",
    goal: 1,
    statKey: "totalWins",
    rarity: "Common",
  },
  {
    id: 2,
    cat: "Battle",
    title: "Sharp Eye",
    iconName: "Eye",
    desc: "50% accuracy",
    goal: 50,
    statKey: "averageAccuracy",
    rarity: "Rare",
  },
  {
    id: 3,
    cat: "Battle",
    title: "Deadshot",
    iconName: "Crosshair",
    desc: "80% accuracy",
    goal: 80,
    statKey: "averageAccuracy",
    rarity: "Epic",
  },
  {
    id: 4,
    cat: "Battle",
    title: "God Aim",
    iconName: "Target",
    desc: "100% accuracy",
    goal: 100,
    statKey: "averageAccuracy",
    rarity: "Legendary",
  },
  {
    id: 5,
    cat: "Battle",
    title: "Veteran",
    iconName: "Sword",
    desc: "Win 100 total matches",
    goal: 100,
    statKey: "totalWins",
    rarity: "Rare",
  },
  {
    id: 6,
    cat: "Battle",
    title: "Apex Predator",
    iconName: "Zap",
    desc: "10 win streak",
    goal: 10,
    statKey: "highestStreak",
    rarity: "Legendary",
  },
  {
    id: 7,
    cat: "Battle",
    title: "Untouchable",
    iconName: "Ghost",
    desc: "50 win streak",
    goal: 50,
    statKey: "highestStreak",
    rarity: "Legendary",
  },

  // --- TREASURY (Scaled for 100k Launch Bonus) ---
  {
    id: 11,
    cat: "Treasury",
    title: "Pocket Change",
    iconName: "Coins",
    desc: "250,000 Coins",
    goal: 250000,
    rarity: "Common",
  },
  {
    id: 12,
    cat: "Treasury",
    title: "Money Bag",
    iconName: "Briefcase",
    desc: "500,000 Coins",
    goal: 500000,
    rarity: "Rare",
  },
  {
    id: 13,
    cat: "Treasury",
    title: "Gold Miner",
    iconName: "Pickaxe",
    desc: "1,000,000 Coins",
    goal: 1000000,
    rarity: "Rare",
  },
  {
    id: 14,
    cat: "Treasury",
    title: "Richie",
    iconName: "Gem",
    desc: "2,500,000 Coins",
    goal: 2500000,
    rarity: "Epic",
  },
  {
    id: 15,
    cat: "Treasury",
    title: "Vault King",
    iconName: "Vault",
    desc: "5,000,000 Coins",
    goal: 5000000,
    rarity: "Epic",
  },
  {
    id: 16,
    cat: "Treasury",
    title: "Half Millionaire",
    iconName: "Banknote",
    desc: "10,000,000 Coins",
    goal: 10000000,
    rarity: "Legendary",
  },
  {
    id: 17,
    cat: "Treasury",
    title: "Millionaire",
    iconName: "Crown",
    desc: "50,000,000 Coins",
    goal: 50000000,
    rarity: "Legendary",
  },
  {
    id: 18,
    cat: "Treasury",
    title: "The Bank",
    iconName: "Landmark",
    desc: "100,000,000 Coins",
    goal: 100000000,
    rarity: "Legendary",
  },

  // --- CAREER ---
  {
    id: 21,
    cat: "Career",
    title: "Newbie",
    iconName: "Baby",
    desc: "Play 5 matches",
    goal: 5,
    statKey: "totalQuizzes",
    rarity: "Common",
  },
  {
    id: 22,
    cat: "Career",
    title: "Rookie",
    iconName: "Footprints",
    desc: "Play 20 matches",
    goal: 20,
    statKey: "totalQuizzes",
    rarity: "Common",
  },
  {
    id: 23,
    cat: "Career",
    title: "Veteran",
    iconName: "Medal",
    desc: "Play 100 matches",
    goal: 100,
    statKey: "totalQuizzes",
    rarity: "Rare",
  },
  {
    id: 24,
    cat: "Career",
    title: "Legend",
    iconName: "Flame",
    desc: "Play 1,000 matches",
    goal: 1000,
    statKey: "totalQuizzes",
    rarity: "Legendary",
  },
  {
    id: 25,
    cat: "Career",
    title: "The GOAT",
    iconName: "ChevronsUp",
    desc: "Play 10,000 matches",
    goal: 10000,
    statKey: "totalQuizzes",
    rarity: "Legendary",
  },

  // --- DAILY ---
  {
    id: 31,
    cat: "Daily",
    title: "Early Bird",
    iconName: "Bird",
    desc: "First win of day",
    goal: 1,
    statKey: "dailyStreak",
    rarity: "Common",
  },
  {
    id: 32,
    cat: "Daily",
    title: "On Fire",
    iconName: "FlameKindling",
    desc: "7 day streak",
    goal: 7,
    statKey: "dailyStreak",
    rarity: "Rare",
  },
  {
    id: 33,
    cat: "Daily",
    title: "Addicted",
    iconName: "HeartPulse",
    desc: "30 day streak",
    goal: 30,
    statKey: "dailyStreak",
    rarity: "Epic",
  },
  {
    id: 34,
    cat: "Daily",
    title: "Loyal Fan",
    iconName: "Infinity",
    desc: "100 day streak",
    goal: 100,
    statKey: "dailyStreak",
    rarity: "Legendary",
  },

  // --- SPECIAL (Difficulty Based) ---
  // Easy
  {
    id: 41,
    cat: "Special",
    title: "Easy Does It",
    iconName: "Coffee",
    desc: "Win 3 Easy matches",
    goal: 3,
    statKey: "easyWins",
    rarity: "Common",
  },
  {
    id: 42,
    cat: "Special",
    title: "Smooth Sailing",
    iconName: "Bike",
    desc: "Win 10 Easy matches",
    goal: 10,
    statKey: "easyWins",
    rarity: "Rare",
  },
  {
    id: 43,
    cat: "Special",
    title: "Easy Rider",
    iconName: "Wind",
    desc: "Win 25 Easy matches",
    goal: 25,
    statKey: "easyWins",
    rarity: "Epic",
  },
  {
    id: 44,
    cat: "Special",
    title: "Cruiser",
    iconName: "Navigation",
    desc: "Win 50 Easy matches",
    goal: 50,
    statKey: "easyWins",
    rarity: "Epic",
  },

  // Medium
  {
    id: 45,
    cat: "Special",
    title: "Rising Star",
    iconName: "Sunrise",
    desc: "Win 3 Medium matches",
    goal: 3,
    statKey: "mediumWins",
    rarity: "Common",
  },
  {
    id: 46,
    cat: "Special",
    title: "Challenger",
    iconName: "Rocket",
    desc: "Win 10 Medium matches",
    goal: 10,
    statKey: "mediumWins",
    rarity: "Rare",
  },
  {
    id: 47,
    cat: "Special",
    title: "Elite Expert",
    iconName: "Dna",
    desc: "Win 25 Medium matches",
    goal: 25,
    statKey: "mediumWins",
    rarity: "Epic",
  },
  {
    id: 48,
    cat: "Special",
    title: "Strategist",
    iconName: "Zap",
    desc: "Win 50 Medium matches",
    goal: 50,
    statKey: "mediumWins",
    rarity: "Legendary",
  },

  // Hard
  {
    id: 49,
    cat: "Special",
    title: "Brainiac",
    iconName: "Brain",
    desc: "Win 3 Hard matches",
    goal: 3,
    statKey: "hardWins",
    rarity: "Rare",
  },
  {
    id: 50,
    cat: "Special",
    title: "Professor",
    iconName: "GraduationCap",
    desc: "Win 10 Hard matches",
    goal: 10,
    statKey: "hardWins",
    rarity: "Epic",
  },
  {
    id: 51,
    cat: "Special",
    title: "Genius",
    iconName: "Lightbulb",
    desc: "Win 25 Hard matches",
    goal: 25,
    statKey: "hardWins",
    rarity: "Legendary",
  },
  {
    id: 52,
    cat: "Special",
    title: "Mastermind",
    iconName: "Cpu",
    desc: "Win 50 Hard matches",
    goal: 50,
    statKey: "hardWins",
    rarity: "Legendary",
  },

  // Mastery
  {
    id: 53,
    cat: "Special",
    title: "Grandmaster",
    iconName: "Axe",
    desc: "Win 250 total matches",
    goal: 250,
    statKey: "totalWins",
    rarity: "Legendary",
  },
];
