export const DEVELOPER_MESSAGES: string[][] = [
    ["Hello, gamer!", "We're finding the best opponents for you.", "This won't take long. Stay tuned!"],
    ["Almost there!", "Matching you with equally skilled players.", "Hold tight, victory awaits!"],
    ["Searching the galaxy for worthy rivals!", "This might take a moment.", "Your patience will be rewarded."],
    ["Great players need great opponents!", "Hang on while we assemble the team.", "This will be epic!"],
    ["We’re on it!", "Scouting for challengers who can keep up.", "Game on in just a moment!"],
    ["Good things take time!", "Finding your next great competition.", "Are you ready to win?"],
    ["Calling all challengers!", "You're just moments away from an epic game.", "Get ready to show your skills!"],
    ["Gathering the best of the best!", "Your opponents are almost ready.", "Keep your game face on!"],
    ["Patience, champion!", "Great matches are worth the wait.", "Stay ready to dominate!"],
    ["Finalizing your match!", "Your rivals will be here soon.", "Sharpen your skills while we finish up."],
    ["Connecting to the game arena!", "Locating worthy opponents for you.", "This will be a match to remember!"],
    ["Players are lining up!", "Your game is about to begin.", "Exciting moments are ahead!"],
    ["Building a battlefield!", "Gathering players from around the globe.", "Prepare to showcase your skills!"],
    ["Hold steady, adventurer!", "Opponents are getting ready for battle.", "Victory is just around the corner!"],
    ["Stay sharp!", "Our system is analyzing players for you.", "Get ready to play with the best!"],
    ["Bringing the action to you!", "Scanning for opponents worldwide.", "The wait will be worth it!"],
    ["Hang in there, warrior!", "We're assembling a legendary lineup.", "Prepare to make your mark!"],
    ["Your match is being prepared!", "Quality opponents are on their way.", "Anticipation makes it sweeter!"],
    ["The stage is being set!", "Players are joining as we speak.", "Stay focused; your time is near!"],
    ["Legends take time to assemble!", "Matching you with your perfect rivals.", "Prepare to write history!"],
    ["We're curating your match!", "Every great game starts with great players.", "Your time is coming soon!"],
    ["Synchronizing players!", "Finding the perfect competition for you.", "Ready your game plan!"],
    ["Just a moment more!", "Opponents are logging in to join you.", "This match will be epic!"],
    ["We’re finalizing the roster!", "It’s almost time to show your skills.", "Stay pumped; it’s happening!"],
    ["Loading opponents!", "Scanning for challenging players.", "Victory loves preparation!"],
    ["Opponents are en route!", "The battle is about to begin.", "Ready yourself for greatness!"],
    ["Your match is almost ready!", "Opponents from around the world are joining.", "Be ready to shine!"],
    ["Hold your excitement!", "Your competition is about to arrive.", "This will be a game worth playing!"],
    ["Gathering challengers!", "Finalizing the game setup.", "Be patient; the fun starts soon!"],
    ["Stay focused, player!", "The competition is forming now.", "Warm up your skills; it’s go time!"]
  ];
  