export const NETWORK = {
  // ───────── CORE PORTS ─────────
  TCP_SERVER_PORT: 41235,

  // ───────── VERSIONING ─────────
  PROTOCOL_VERSION: "2.0.0",
  GAME_VERSION: "3.0.0",

  // ───────── HANDSHAKE ─────────
  HANDSHAKE_TIMEOUT: 5000,
  MAX_CLIENTS: 4,

  // ───────── HEARTBEAT ─────────
  HEARTBEAT_INTERVAL: 3000,
  HEARTBEAT_MISS_THRESHOLD: 3,

  // ───────── TCP SAFETY ─────────
  MAX_PACKET_SIZE: 1_048_576,

  // ───────── RECONNECT ─────────
  RECONNECT_ATTEMPTS: 2,
  RECONNECT_INTERVAL_MS: 1000,
  RECONNECT_BACKOFF_MULTIPLIER: 1.5,
  RECONNECT_TIMEOUT_MS: 20000,

  // ───────── MESSAGE TYPES ─────────
  PLAYER_JOIN: "PLAYER_JOIN",
  PLAYER_JOIN_REJECT: "PLAYER_JOIN_REJECT",
  PLAYER_LEAVE: "PLAYER_LEAVE",
  PLAYER_LIST_UPDATE: "PLAYER_LIST_UPDATE",

  PING: "PING",
  PONG: "PONG",

  JOIN_REQUEST: "JOIN_REQUEST",
  JOIN_ACCEPT: "JOIN_ACCEPT",
  JOIN_DENY: "JOIN_DENY",

  RECONNECT_REQUEST: "RECONNECT_REQUEST",
  RECONNECT_SUCCESS: "RECONNECT_SUCCESS",
  RECONNECT_FAIL: "RECONNECT_FAIL",
  SYNC_STATE: "SYNC_STATE",

  PLAYER_RECONNECTING: "PLAYER_RECONNECTING",
  PLAYER_RECONNECTED: "PLAYER_RECONNECTED",
  RECONNECT_FAILED_MATCH_DISMISSED: "RECONNECT_FAILED_MATCH_DISMISSED",
  REQUEST_REJOIN_MATCH: "REQUEST_REJOIN_MATCH",
  REJOIN_MATCH_ACCEPTED: "REJOIN_MATCH_ACCEPTED",
  REJOIN_MATCH_REJECTED: "REJOIN_MATCH_REJECTED",
  MATCH_PAUSED_FOR_RECONNECT: "MATCH_PAUSED_FOR_RECONNECT",
  MATCH_RESUMED_AFTER_RECONNECT: "MATCH_RESUMED_AFTER_RECONNECT",

  UPDATE_REQUIRED: "UPDATE_REQUIRED",
};

export const MODES = {
  CHOR_POLICE: {
    ID: "CHOR_POLICE",
    GAME_START: "CP_GAME_START",
    GAME_END: "CP_GAME_END",
    ROLE_ASSIGN: "CP_ROLE_ASSIGN",
    PUBLIC_REVEAL: "CP_PUBLIC_REVEAL",
    POLICE_GUESS: "CP_POLICE_GUESS",
    ROUND_RESULT: "CP_ROUND_RESULT",
    ROUND_START: "CP_ROUND_START",
    SCORE_QUIZ_TURN: "CP_SCORE_QUIZ_TURN",
    SCORE_GUESS: "CP_SCORE_GUESS",
    SCORE_GUESS_RESULT: "CP_SCORE_GUESS_RESULT",
    SCORE_QUIZ_NEXT: "CP_SCORE_QUIZ_NEXT",
    POLICE_TURN_READY: "CP_POLICE_TURN_READY",
  },
  THINK_AND_COUNT: {
    ID: "THINK_AND_COUNT",
    GAME_START: "TC_GAME_START",
    GAME_END: "TC_GAME_END",
    ANSWER_PREFIX: "TC_ANSWER_",
    ANSWER_SUBMITTED: "TC_ANSWER_SUBMITTED",
    QUESTION_SYNC: "TC_QUESTION_SYNC",
    DIFFICULTY_CHANGE: "TC_DIFFICULTY_CHANGE",
    QUESTION_TIME_LIMIT: 10000,
  },
};
