export const NETWORK = {
  // ───────── CORE PORTS ─────────
  DISCOVERY_PORT: 41234,
  TCP_SERVER_PORT: 41235,
  BROADCAST_ADDRESS: "255.255.255.255",

  // ───────── VERSIONING ─────────
  PROTOCOL_VERSION: "2.0.0",
  GAME_VERSION: "3.0.0",

  // ───────── DISCOVERY ─────────
  DISCOVERY_TIMEOUT: 5000,

  

  // ───────── HANDSHAKE ─────────
  HANDSHAKE_TIMEOUT: 5000, // max wait for join_request
  MAX_CLIENTS: 4,

  // ───────── HEARTBEAT ─────────
  HEARTBEAT_INTERVAL: 3000, // ping every 3s
  HEARTBEAT_MISS_THRESHOLD: 3, // tolerate 3 misses

  // ───────── TCP SAFETY ─────────
  MAX_PACKET_SIZE: 1_048_576, // 1MB (same as transport)

  // ───────── RECONNECT ─────────
  RECONNECT_ATTEMPTS: 2, // decreased for faster disconnect detection
  RECONNECT_INTERVAL_MS: 1000, // base delay
  RECONNECT_BACKOFF_MULTIPLIER: 1.5, // exponential growth

  // ───────── MESSAGE TYPES ─────────
  DISCOVERY_MSG: "PLATFORM_DISCOVERY",
  RESPONSE_MSG: "PLATFORM_RESPONSE",

  PLAYER_JOIN: "PLAYER_JOIN",
  PLAYER_JOIN_REJECT: "PLAYER_JOIN_REJECT",
  PLAYER_LEAVE: "PLAYER_LEAVE",
  PLAYER_LIST_UPDATE: "PLAYER_LIST_UPDATE",

  PING: "PING",
  PONG: "PONG",

  // 🔥 NEW (important)
  JOIN_REQUEST: "JOIN_REQUEST",
  JOIN_ACCEPT: "JOIN_ACCEPT",
  JOIN_DENY: "JOIN_DENY",
};

export const MODES = {
  CHOR_POLICE: {
    ID: "CHOR_POLICE",
    GAME_START: "CP_GAME_START",
    GAME_END: "CP_GAME_END",
    ROLE_ASSIGN: "CP_ROLE_ASSIGN",
    PUBLIC_REVEAL: "CP_PUBLIC_REVEAL",
    POLICE_GUESS: "CP_POLICE_GUESS",
    ROUND_RESULT: "CP_ROUND_RESULT",
    ROUND_START: "CP_ROUND_START",
    SCORE_QUIZ_TURN: "CP_SCORE_QUIZ_TURN",
    SCORE_GUESS: "CP_SCORE_GUESS",
    SCORE_GUESS_RESULT: "CP_SCORE_GUESS_RESULT",
  },
  THINK_AND_COUNT: {
    ID: "THINK_AND_COUNT",
    GAME_START: "TC_GAME_START",
    GAME_END: "TC_GAME_END",
    ANSWER_PREFIX: "TC_ANSWER_",
    ANSWER_SUBMITTED: "TC_ANSWER_SUBMITTED",
    QUESTION_SYNC: "TC_QUESTION_SYNC",
    DIFFICULTY_CHANGE: "TC_DIFFICULTY_CHANGE",
    QUESTION_TIME_LIMIT: 10000,
  },
};
