export const WIN_MESSAGES = [
  "Great job, {name}!",
  "Well done, {name}!",
  "You nailed it, {name}!",
  "Awesome, {name}!",
  "You did it, {name}!",
  "Fantastic work, {name}!",
  "You're unstoppable, {name}!",
  "Incredible job, {name}!",
  "You're a champion, {name}!",
  "Amazing win, {name}!",
  "Bravo, {name}! You did it!",
  "You're on fire, {name}!",
  "Victory is yours, {name}!",
  "Well-deserved win, {name}!",
  "You crushed it, {name}!",
  "You’re a superstar, {name}!",
  "Excellent play, {name}!",
  "You’re a true winner, {name}!",
  "Top-notch performance, {name}!",
  "Way to go, {name}!",
  "You outdid yourself, {name}!",
  "You're amazing, {name}!",
  "That was superb, {name}!",
  "Keep shining, {name}!",
  "Victory suits you, {name}!",
  "Sensational effort, {name}!",
  "What a win, {name}!",
  "You make it look easy, {name}!",
  "Keep up the great work, {name}!",
  "Magnificent, {name}!",
  "You really wowed us, {name}!",
  "Your hard work paid off, {name}!",
  "Remarkable performance, {name}!",
  "Kudos to you, {name}!",
  "You’re an inspiration, {name}!",
];

export const LOSS_MESSAGES = [
  "Oh no, {name}!",
  "Better luck next time, {name}!",
  "Oops, {name}!",
  "So close, {name}!",
  "Try again, {name}!",
  "Not this time, {name}!",
  "Almost, {name}!",
  "Good try, {name}!",
  "Close one, {name}!",
  "You’ll get it next time, {name}!",
  "Better luck next round, {name}!",
  "Try again, {name}!",
  "Almost there, {name}!",
  "Close call, {name}!",
  "That was close, {name}!",
  "Next time, {name}!",
  "Keep it up, {name}!",
  "Stay positive, {name}!",
];
