export const WIN_MESSAGES = [
  "Great job, {name}!",
  "Well done, {name}!",
  "You nailed it, {name}!",
  "Awesome, {name}!",
  "You did it, {name}!",
  "Fantastic work, {name}!",
  "You're unstoppable, {name}!",
  "Incredible job, {name}!",
  "You're a champion, {name}!",
  "Amazing win, {name}!",
  "Bravo, {name}! You did it!",
  "You're on fire, {name}!",
  "Victory is yours, {name}!",
  "Well-deserved win, {name}!",
  "You crushed it, {name}!",
  "You’re a superstar, {name}!",
  "Excellent play, {name}!",
  "You’re a true winner, {name}!",
  "Top-notch performance, {name}!",
  "Way to go, {name}!",
  "You outdid yourself, {name}!",
  "You're amazing, {name}!",
  "That was superb, {name}!",
  "Keep shining, {name}!",
  "Victory suits you, {name}!",
  "Sensational effort, {name}!",
  "What a win, {name}!",
  "You make it look easy, {name}!",
  "Keep up the great work, {name}!",
  "Magnificent, {name}!",
  "You really wowed us, {name}!",
  "Your hard work paid off, {name}!",
  "Remarkable performance, {name}!",
  "Kudos to you, {name}!",
  "You’re an inspiration, {name}!",
];

export const LOSS_MESSAGES = [
  "Oh no , {name}!",
  "Better luck next time, {name}!",
  "Oops, {name}!",
  "So close, {name}!",
  "Try again, {name}!",
  "Not this time, {name}!",
  "Almost, {name}!",
  "Good try, {name}!",
  "Close one, {name}!",
  "You’ll get it next time, {name}!",
  "Better luck next round, {name}!",
  "Try again, {name}!",
  "Almost there, {name}!",
  "Close call, {name}!",
  "That was close, {name}!",
  "Next time, {name}!",
  "Keep it up, {name}!",
  "Stay positive, {name}!",
];

export const THINKING_MESSAGES = [
  "Hold on, {name} is thinking hard...",
  "{name} is taking a moment to decide!",
  "Hmm... {name} is making a move.",
  "{name} is brainstorming the best option.",
  "Give {name} a second to think...",
  "Thinking caps on! {name} is working.",
  "One moment, {name} is deciding...",
  "{name} is carefully planning their next step.",
  "Wait a bit, {name} is coming up with something!",
  "Patience! {name} is deep in thought.",
  "Just a moment, {name} is figuring it out.",
  "{name} is piecing things together...",
  "Almost there... {name} is almost ready!",
  "{name} is reviewing their options.",
  "Let {name} take a quick pause to think.",
  "Thinking... {name} is about to make a choice!",
  "It’s all coming together for {name}!",
  "Give {name} a moment... the idea is forming!",
  "Shh... {name} is in deep thought.",
  "Wait for it... {name} is getting ready!",
  "{name} is calculating the best move.",
  "Wait... {name} is considering all the options.",
  "Give {name} a few more seconds to think.",
  "{name} is analyzing the situation carefully.",
  "{name} is weighing the choices...",
  "{name} is deciding the perfect plan!",
  "{name} is finding the right answer...",
  "{name} is organizing their thoughts.",
  "Hmm... {name} is still thinking it through.",
  "Just a little more time... {name} is almost ready!",
  "Almost there... {name} is about to choose!",
  "Hang tight... {name} is almost done thinking!",
  "Give {name} a moment to sort things out.",
];


export const WIN_MESSAGES_WITHOUT_NAME = [
  "Great job!",
  "Well done!",
  "You nailed it!",
  "Awesome work!",
  "You did it!",
  "Fantastic effort!",
  "You're unstoppable!",
  "Incredible performance!",
  "You're a champion!",
  "Amazing win!",
  "Bravo! You did it!",
  "You're on fire!",
  "Victory is yours!",
  "Well-deserved win!",
  "You crushed it!",
  "You’re a superstar!",
  "Excellent play!",
  "You’re a true winner!",
  "Top-notch performance!",
  "Way to go!",
  "You outdid yourself!",
  "You're amazing!",
  "That was superb!",
  "Keep shining!",
  "Victory suits you!",
  "Sensational effort!",
  "What a win!",
  "You make it look easy!",
  "Keep up the great work!",
  "Magnificent!",
  "You really wowed us!",
  "Your hard work paid off!",
  "Remarkable performance!",
  "Kudos to you!",
  "You’re an inspiration!",
];

export const LOSS_MESSAGES_WITHOUT_NAME = [
  "Not quite right, but keep going!",
  "Oops, that wasn’t it! Don’t give up!",
  "Close call! Try the next one!",
  "Almost had it! You’ve got this!",
  "So close! Stay confident!",
  "Not this time, but you’re doing great!",
  "Keep going! You’ll nail it next time!",
  "Good effort! Let’s move on to the next!",
  "It’s okay to miss one; you’re learning!",
  "Great attempt! Keep trying!",
  "Close, but not quite! Try again!",
  "Missed it this time, but you’re on the right track!",
  "It’s all part of the game—don’t stop now!",
  "You’re getting closer, keep it up!",
  "No worries! Every step counts!",
  "You’re doing great! Let’s keep moving forward!",
  "Take a deep breath and focus on the next one!",
  "Shake it off! You’ll ace the next question!",
];



export const WINNER_MESSAGES = [
  "You’re a natural-born champion!",
  "Congratulations, victory is yours!",
  "You’ve mastered the art of winning!",
  "Your determination paid off!",
  "You make success look easy!",
  "A spectacular win—well deserved!",
  "You’ve raised the bar for everyone!",
  "Outstanding performance—bravo!",
  "Victory is just a habit for you!",
  "Your hard work truly shined!",
  "This win is a testament to your skills!",
  "You're on top of the world!",
  "Hats off to your amazing effort!",
  "Unstoppable energy, unbeatable results!",
  "You’ve proven your brilliance yet again!",
  "What a breathtaking performance!",
  "You’ve conquered the challenge in style!",
  "You’ve claimed the crown of success!",
  "Every effort of yours deserves applause!",
  "Celebrate your well-earned triumph!",
  "You’ve earned every bit of this victory!",
  "Your effort and persistence have paid off!",
  "You showed true skill in every move!",
  "Winning looks good on you!",
  "You’ve set a new standard of excellence!",
  "Your talent is unmatched!",
  "This win is just the beginning of many more!",
  "You’ve outdone yourself, congratulations!",
  "A win like that takes real dedication!",
  "You’re a legend in the making!",
  "You’ve earned this with your brilliance!",
  "Every move was perfect—you nailed it!",
  "That was a masterclass in success!",
  "Nothing can stop you now—well done!",
  "You’re the definition of a winner!",
  "Your victory is inspiring to all!",
  "Success looks effortless when it’s you!",
  "Amazing performance—you’ve set the bar high!",
  "Your win is a direct result of your hard work!",
  "What an incredible achievement!"
];

export const LOSER_MESSAGES = [
  "Every setback is a setup for a comeback.",
  "Keep your head up; the next win is yours!",
  "You gave it your all—well done!",
  "Every champion was once a contender who refused to give up.",
  "Great effort! Winning is just around the corner.",
  "Your journey to success is still in progress.",
  "Each step brings you closer to victory!",
  "You played with heart—that’s what matters.",
  "Failure is the stepping stone to greatness.",
  "Next time will be your time to shine!",
  "You’re learning, growing, and improving every time!",
  "Stay strong—success is built on perseverance.",
  "You’re already a winner for trying your best!",
  "Don’t give up; greatness takes time.",
  "Every great player knows the taste of defeat.",
  "You’re one step closer to achieving your goal!",
  "Keep pushing forward—you’re unstoppable!",
  "Your effort was inspiring—keep going!",
  "Defeat is only temporary; greatness is forever.",
  "Believe in yourself—the best is yet to come!",
  "Don't be discouraged, next time will be yours!",
  "Every loss teaches something new. You’re growing!",
  "Failure is part of success—keep going!",
  "It’s not the end; it’s just the beginning of your journey!",
  "The best come back stronger after setbacks!",
  "The greatest come from failure. You’ll bounce back!",
  "You’ve got this! Learn and rise again!",
  "Keep pushing—every effort gets you closer to success!",
  "Failure doesn’t define you. Keep moving forward!",
  "The road to victory is paved with challenges—stay strong!",
  "Even champions have their down moments—keep trying!",
  "Success is born from perseverance—don’t stop now!",
  "You’ve shown heart, and that’s what counts!",
  "You’ll win next time—just keep believing!",
  "Setbacks are just setups for comebacks!",
  "You’re getting better with every challenge!",
  "Victory is waiting for you—keep up the hard work!",
  "Keep your chin up—tomorrow is another opportunity!",
  "You are one step closer to your goal—keep going!",
  "Great things are ahead. Keep striving!"
];

export const TIMES_UP_MESSAGES_FOR_KIDS = [
  "Oh no, time’s up! Let’s try the next one!",
  "The clock ran out! You’ll be quicker next time!",
  "Oops! Time’s up! Keep going, you’re doing great!",
  "Too slow this time, but don’t give up!",
  "Time’s up! You can do it on the next one!",
  "Oh dear, the timer stopped! Let’s try again!",
  "Uh-oh, the clock beat you! Ready for the next?",
  "Ran out of time? No worries, keep trying!",
  "Don’t worry, time’s up! Let’s keep playing!",
  "Oopsie! Time’s out! You’ll get it next time!",
];
