export const WIN_MESSAGES = [
  "Great job, {name}!",
  "Well done, {name}!",
  "You nailed it, {name}!",
  "Awesome, {name}!",
  "You did it, {name}!",
  "Fantastic work, {name}!",
  "You're unstoppable, {name}!",
  "Incredible job, {name}!",
  "You're a champion, {name}!",
  "Amazing win, {name}!",
  "Bravo, {name}! You did it!",
  "You're on fire, {name}!",
  "Victory is yours, {name}!",
  "Well-deserved win, {name}!",
  "You crushed it, {name}!",
  "You’re a superstar, {name}!",
  "Excellent play, {name}!",
  "You’re a true winner, {name}!",
  "Top-notch performance, {name}!",
  "Way to go, {name}!",
  "You outdid yourself, {name}!",
  "You're amazing, {name}!",
  "That was superb, {name}!",
  "Keep shining, {name}!",
  "Victory suits you, {name}!",
  "Sensational effort, {name}!",
  "What a win, {name}!",
  "You make it look easy, {name}!",
  "Keep up the great work, {name}!",
  "Magnificent, {name}!",
  "You really wowed us, {name}!",
  "Your hard work paid off, {name}!",
  "Remarkable performance, {name}!",
  "Kudos to you, {name}!",
  "You’re an inspiration, {name}!",
];

export const LOSS_MESSAGES = [
  "Oh no, {name}!",
  "Better luck next time, {name}!",
  "Oops, {name}!",
  "So close, {name}!",
  "Try again, {name}!",
  "Not this time, {name}!",
  "Almost, {name}!",
  "Good try, {name}!",
  "Close one, {name}!",
  "You’ll get it next time, {name}!",
  "Better luck next round, {name}!",
  "Try again, {name}!",
  "Almost there, {name}!",
  "Close call, {name}!",
  "That was close, {name}!",
  "Next time, {name}!",
  "Keep it up, {name}!",
  "Stay positive, {name}!",
];

export const THINKING_MESSAGES = [
  "Hold on, {name} is thinking hard...",
  "{name} is taking a moment to decide!",
  "Hmm... {name} is making a move.",
  "{name} is brainstorming the best option.",
  "Give {name} a second to think...",
  "Thinking caps on! {name} is working.",
  "One moment, {name} is deciding...",
  "{name} is carefully planning their next step.",
  "Wait a bit, {name} is coming up with something!",
  "Patience! {name} is deep in thought.",
  "Just a moment, {name} is figuring it out.",
  "{name} is piecing things together...",
  "Almost there... {name} is almost ready!",
  "{name} is reviewing their options.",
  "Let {name} take a quick pause to think.",
  "Thinking... {name} is about to make a choice!",
  "It’s all coming together for {name}!",
  "Give {name} a moment... the idea is forming!",
  "Shh... {name} is in deep thought.",
  "Wait for it... {name} is getting ready!",
  "{name} is calculating the best move.",
  "Wait... {name} is considering all the options.",
  "Give {name} a few more seconds to think.",
  "{name} is analyzing the situation carefully.",
  "{name} is weighing the choices...",
  "{name} is deciding the perfect plan!",
  "{name} is finding the right answer...",
  "{name} is organizing their thoughts.",
  "Hmm... {name} is still thinking it through.",
  "Just a little more time... {name} is almost ready!",
  "Almost there... {name} is about to choose!",
  "Hang tight... {name} is almost done thinking!",
  "Give {name} a moment to sort things out.",
];
