export const generateSmartReview = (rating: number): string => {
  const fiveStarReviews = [
    "Absolutely love this game! The concept is unique and super fun to play.",
    "One of the best strategy games I've played. Smooth UI and addictive gameplay!",
    "Amazing experience! The design and animations are top notch.",
    "Very engaging and well-built. Highly recommended!",
    "Fantastic game! Keeps me entertained every single day.",
    "Super creative idea! I didn’t expect it to be this addictive.",
    "The UI feels premium and the gameplay is smooth.",
    "Honestly impressed by how polished this game is.",
    "Great balance between fun and challenge.",
    "Clean design, no unnecessary clutter. Love it!",
    "Very satisfying gameplay mechanics.",
    "Brilliant concept executed perfectly.",
    "The animations make the experience even better.",
    "Smooth performance and no lag at all.",
    "I keep coming back to this game daily!",
    "Highly enjoyable and thoughtfully designed.",
    "Simple yet very engaging gameplay.",
    "Perfect game to play with friends.",
    "The strategy aspect makes it exciting.",
    "Absolutely worth downloading!",
    "Love the clean interface and smart design.",
    "One of the most entertaining games on my phone.",
    "Very creative and refreshing experience.",
    "Everything feels well optimized.",
    "Great job by the developer!",
    "This game deserves more recognition.",
    "Fun, fast, and very engaging.",
    "Addictive in the best way possible.",
    "Excellent concept and execution.",
    "Love how smooth everything feels.",
    "Very well structured gameplay.",
    "Keeps me hooked every time I play.",
    "Beautiful UI and smooth transitions.",
    "Definitely a 5 star experience.",
    "The challenges are really enjoyable.",
    "Impressive attention to detail.",
    "It’s rare to find such a polished game.",
    "Really well made and super fun.",
    "Great mix of strategy and excitement.",
    "Works flawlessly on my device.",
    "Easy to understand but hard to master.",
    "Super engaging and rewarding.",
    "Well balanced and thoughtfully built.",
    "I genuinely enjoy playing this.",
    "The gameplay flow is amazing.",
    "Feels like a premium experience.",
    "One of my favorite mobile games.",
    "Totally exceeded my expectations.",
    "Brilliant and entertaining!",
    "Highly recommended for everyone.",

    "Outstanding gameplay and smooth experience.",
    "Extremely fun and addictive!",
    "The design quality is exceptional.",
    "Plays perfectly without any issues.",
    "Great work! Everything feels polished.",
    "Super smooth and satisfying to play.",
    "Love the strategy involved in this.",
    "Very enjoyable and rewarding game.",
    "This game keeps getting better.",
    "Impressive performance and visuals.",
    "Very clever and creative concept.",
    "Well optimized and beautifully designed.",
    "Gameplay feels fresh and exciting.",
    "A must-play for strategy lovers.",
    "Very smooth and user-friendly.",
    "Exceptional mobile gaming experience.",
    "Perfect blend of fun and logic.",
    "Addictive and very well built.",
    "Everything works flawlessly.",
    "Truly a 5-star worthy game.",
    "Really impressed with the quality.",
    "Very smooth animations and transitions.",
    "Feels like a professionally made game.",
    "Highly entertaining and engaging.",
    "Top-tier mobile gaming experience.",
    "Great replay value.",
    "Well designed and easy to play.",
    "Fun from start to finish.",
    "Very immersive gameplay.",
    "Fantastic execution of a great idea.",
    "The interface is very intuitive.",
    "Smooth, stable, and super fun.",
    "I play this almost every day!",
    "Amazing attention to detail.",
    "Very creative and exciting.",
    "Super polished and refined.",
    "Excellent pacing and flow.",
    "Love every part of this game.",
    "Very responsive and smooth.",
    "Definitely deserves 5 stars.",
    "Great game mechanics.",
    "Feels rewarding after every round.",
    "Fun and competitive gameplay.",
    "High-quality experience overall.",
    "Very enjoyable time killer.",
    "Smart and addictive concept.",
    "Great visuals and performance.",
    "Simple, smooth, and fun.",
    "Super entertaining experience.",
    "Well executed and impressive."
  ];

  const fourStarReviews = [
    "Really fun game with great potential. Enjoying it a lot!",
    "Nice concept and smooth performance. Keep improving!",
    "Good gameplay and creative idea. Worth trying!",
    "Enjoyable and well designed game.",
    "Great effort by the developer. Looking forward to updates!",
    "Fun experience overall.",
    "Interesting concept and smooth UI.",
    "Pretty engaging and well built.",
    "Good balance of fun and strategy.",
    "Nice design and clean interface.",
    "Solid gameplay mechanics.",
    "Runs smoothly on my device.",
    "I enjoy playing it casually.",
    "Creative and refreshing idea.",
    "Nice work on the animations.",
    "Very playable and enjoyable.",
    "Good game with room to grow.",
    "Simple but entertaining.",
    "Feels polished and smooth.",
    "Interesting approach to gameplay.",
    "Well structured and easy to understand.",
    "Good effort from the developer.",
    "Fun to play with friends.",
    "Nice UI and smooth transitions.",
    "Entertaining and engaging.",
    "Good experience overall.",
    "Enjoying it so far.",
    "Well optimized and stable.",
    "Nice strategy element included.",
    "Smooth controls and gameplay.",
    "Interesting mechanics.",
    "Good concept executed nicely.",
    "Clean layout and design.",
    "Pretty addictive at times.",
    "Nice attention to detail.",
    "Fun and competitive.",
    "Worth downloading.",
    "Good updates could make it even better.",
    "Smooth and responsive.",
    "Enjoyable daily game.",
    "Nice challenge level.",
    "Works well without issues.",
    "Good overall experience.",
    "Creative and engaging.",
    "Nice small game to pass time.",
    "Very decent gameplay.",
    "I like the overall idea.",
    "Smooth animations and layout.",
    "Fun concept and execution.",
    "Looking forward to future updates.",

    "Nice effort and enjoyable gameplay.",
    "Good performance and smooth UI.",
    "Fun concept with potential.",
    "Very playable and entertaining.",
    "Works well most of the time.",
    "Nice strategy experience.",
    "Well designed overall.",
    "Good balance and pacing.",
    "Enjoyable and stable.",
    "Pretty smooth gameplay.",
    "Nice creative touch.",
    "Fun mechanics and flow.",
    "Decent challenge level.",
    "Well optimized for mobile.",
    "Interesting and fun.",
    "Nice gameplay structure.",
    "Smooth and enjoyable.",
    "Good replay value.",
    "Nice user experience.",
    "Creative execution.",
    "Solid overall design.",
    "Fun but could use more features.",
    "Good concept and presentation.",
    "Very engaging gameplay.",
    "Runs smoothly without lag.",
    "Nice competitive element.",
    "Clean and simple interface.",
    "Entertaining experience.",
    "Good stability and flow.",
    "Very responsive controls.",
    "Nice idea and good execution.",
    "Well balanced gameplay.",
    "Fun to play occasionally.",
    "Decent polish overall.",
    "Good strategy component.",
    "Nice pacing and structure.",
    "Works as expected.",
    "Smooth and stable performance.",
    "Good attention to detail.",
    "Interesting gameplay loop.",
    "Nice visuals and design.",
    "Fun and relaxing experience.",
    "Pretty enjoyable overall.",
    "Good foundation for future updates.",
    "Nice smooth transitions.",
    "Creative and interactive.",
    "Well made casual game.",
    "Nice mechanics and controls.",
    "Solid mobile experience.",
    "Good quality game overall."
  ];

  const pool = rating === 5 ? fiveStarReviews : fourStarReviews;

  return pool[Math.floor(Math.random() * pool.length)];
};
