export const generateSmartReview = (rating: number): string => {
  const fiveStarReviews = [
    "Honestly this game is so fun, especially when you play with friends and everyone starts suspecting each other.",
    "Raja Mantri Chor Sipahi brought back so many childhood memories, but this mobile version feels way more convenient.",
    "The whole guessing part is actually crazy fun because you never know who is secretly playing the Chor.",
    "Played this with my friends and we were literally arguing every round about who the Chor was.",
    "Such a simple concept but somehow every round becomes super competitive and hilarious with friends.",
    "The multiplayer mode is honestly the best part, especially when everyone starts making random accusations.",
    "I did not expect this classic game to be this addictive, but I keep playing another round.",
    "The suspense before finding out everyone's role makes every round feel different and genuinely exciting.",
    "Really love how the classic Raja Mantri Chor Sipahi concept works so smoothly as a mobile game.",
    "This is actually such a fun game for friends, especially when everyone starts bluffing and guessing.",
    "The gameplay is simple to understand but still makes you think carefully about everyone's actions.",
    "Every round has some unexpected moment that makes you want to immediately play another one.",
    "The Chor guessing mechanic is genuinely fun because sometimes your first guess is completely wrong.",
    "This game is perfect when friends are together and you want something quick but actually competitive.",
    "The rounds are quick enough to stay interesting, but somehow I always end up playing more.",
    "Really enjoyed the strategy part because you have to pay attention instead of randomly choosing someone.",
    "The classic game feels surprisingly fresh here, and playing it digitally makes everything much easier.",
    "I love the mind games during each round, especially when everyone starts defending themselves suspiciously.",
    "Playing multiplayer with friends makes this ten times better because every person has a different strategy.",
    "The game gives such a nostalgic feeling while still having a modern mobile gaming experience.",
    "Honestly one of those games where you download it casually and suddenly spend an hour playing.",
    "The guessing and role system makes every round unpredictable, which keeps the gameplay really entertaining.",
    "Really fun experience overall, especially trying to figure out who is actually the Chor.",
    "The game is easy enough for anyone to understand, but the guessing makes it surprisingly competitive.",
    "Had such a good time playing this with friends, especially when everyone's accusations started getting ridiculous.",
    "The multiplayer experience feels really fun because you never know what another player is planning.",
    "Love how every round creates a completely different situation depending on everyone's guesses and decisions.",
    "This game genuinely captures the fun of playing Raja Mantri Chor Sipahi with friends.",
    "The gameplay feels quick, smooth, and entertaining without making the rules unnecessarily complicated.",
    "Really liked the suspense when waiting to see whether my guess about the Chor was correct.",
    "This is honestly a perfect casual game when you have friends around and want quick entertainment.",
    "The role-based gameplay gives everyone something interesting to do instead of making rounds feel repetitive.",
    "I really enjoy the competitive feeling when everyone starts trying to prove they are innocent.",
    "The game is simple but the social guessing makes it way more fun than I expected.",
    "Really impressed with how well this childhood game translates into a proper mobile experience.",
    "Every match feels like a mini mystery where everyone is trying to figure out what happened.",
    "The multiplayer rounds are honestly hilarious when everyone confidently accuses the completely wrong person.",
    "The combination of guessing, strategy, and random situations makes this game super replayable.",
    "I like that the game doesn't take forever because you can finish a round pretty quickly.",
    "This is such a fun way to play the classic game without needing physical cards anymore.",
    "Really enjoyed the overall experience, especially the moments when the actual Chor completely fools everyone.",
    "The game has that perfect casual vibe but still gets surprisingly competitive when playing with friends.",
    "The guessing mechanics are probably my favorite part because every player can try different strategies.",
    "Really fun concept and the multiplayer makes it even better when you have a group ready.",
    "I keep thinking I have figured out the Chor and then somehow get completely fooled.",
    "The gameplay is straightforward, but the social aspect makes every round feel fresh and unpredictable.",
    "Honestly had way more fun than expected, especially after getting a few friends into multiplayer.",
    "The classic Raja Mantri Chor Sipahi experience feels really nice when played together on mobile.",
    "Every round gives you a reason to pay attention because one wrong guess can change everything.",
    "Really entertaining game with friends, and the suspense around everyone's hidden role never gets boring.",
    "The best part is watching everyone confidently choose someone and then discovering they were completely wrong.",
    "This game somehow turns a very simple childhood concept into something genuinely fun on mobile.",
    "I love how competitive things become when everyone starts trying to figure out the hidden roles.",
    "The Chor role is honestly hilarious because sometimes you can completely fool everyone without trying.",
    "Really enjoyed playing different rounds because the winner can change depending on everyone's decisions.",
    "This is the kind of multiplayer game where one round somehow turns into five more.",
    "The game feels especially fun when everyone knows the classic rules and starts playing strategically.",
    "I like how every player has to stay involved instead of just waiting for their turn.",
    "The suspense before the final reveal is genuinely satisfying when your prediction turns out correct.",
    "Really fun game for family and friends because the rules are easy enough for everyone.",
    "The strategy is subtle but definitely there, especially when trying to understand everyone's behavior.",
    "Had some genuinely funny moments playing this because nobody trusted anyone after a few rounds.",
    "The classic concept plus mobile convenience makes this something I can easily play anytime.",
    "Every multiplayer match feels different because the people playing completely change the experience.",
    "Really liked the guessing system because it rewards paying attention instead of simply tapping randomly.",
    "This game has that perfect balance where the rules are simple but the matches become competitive.",
    "Playing with friends makes the accusations and reactions ten times funnier than playing alone.",
    "The nostalgia is real, but the mobile version still feels fresh enough to keep playing.",
    "I genuinely enjoy trying to read everyone's choices and figuring out who might be Chor.",
    "The rounds move quickly, which makes it really easy to keep the momentum going.",
    "This game is surprisingly entertaining for something that has such simple core mechanics.",
    "Really liked how the hidden roles create suspense without making the game difficult to understand.",
    "The multiplayer experience is where this game really shines because everyone's personality changes their strategy.",
    "Had a blast playing this with friends because every person had a completely different guessing style.",
    "I love when everyone thinks they know the Chor and then the reveal proves everyone wrong.",
    "The game is simple enough for casual players but still gives experienced players room for strategy.",
    "Really enjoyable concept and the short rounds make it easy to fit into random free time.",
    "This brought back the exact feeling of playing Chor Police growing up, just in a much easier format.",
    "The guessing moments are genuinely satisfying when you manage to identify the Chor correctly.",
    "Really fun multiplayer game where the social part makes even losing rounds entertaining.",
    "The role system makes everyone suspicious, which is honestly what makes the game so funny.",
    "I like that every match creates new stories because the guesses and outcomes are never identical.",
    "This game gets surprisingly intense when everyone is trying to prove their guess is correct.",
    "The best rounds are when the actual Chor stays completely unnoticed until the final reveal.",
    "Really liked playing this with friends because the game creates natural competition without complicated rules.",
    "The childhood nostalgia combined with quick mobile matches makes this a really enjoyable experience.",
    "Every round makes me want to test whether I can predict the Chor better than everyone else.",
    "I honestly expected a basic game but the multiplayer guessing makes it much more interesting.",
    "The gameplay is easy to pick up, but playing against smart friends makes it surprisingly challenging.",
    "Really entertaining game for groups because everyone gets involved and has something to guess.",
    "The suspense, guessing, and reactions from other players make the matches genuinely enjoyable.",
    "This is one of those games where the simple idea works because the players create the fun.",
    "Really enjoyed the competitive guessing and the unexpected results that happen during multiplayer rounds.",
    "The game feels nostalgic without feeling outdated, which is probably my favorite thing about it.",
    "Had a lot of fun trying different guessing strategies instead of always choosing the obvious player.",
    "The Chor role creates so many funny moments when someone manages to stay completely unnoticed.",
    "Really good casual multiplayer experience when you want something quick, social, and competitive.",
    "The rounds are short but still have enough suspense to make you care about the outcome.",
    "I love how quickly everyone becomes suspicious of each other once the guessing starts.",
    "This is genuinely fun with friends because the game gives everyone reasons to argue about their guesses.",
    "The classic Raja Mantri Chor Sipahi idea works perfectly for quick mobile multiplayer matches.",
    "Really enjoyed the hidden-role gameplay because every player has a different reason to act suspicious.",
    "The final reveal is always satisfying, especially when your guess was right from the beginning.",
    "This game has become way more fun after introducing it to a few friends.",
    "Really entertaining experience that feels casual at first but becomes surprisingly competitive after a few rounds.",
    "The guessing mechanics keep the game from feeling repetitive even though the basic rules stay simple.",
    "Honestly one of the better games for quick multiplayer sessions with friends and family.",
    "I like how the game rewards observation and guessing rather than requiring complicated controls.",
    "The whole experience feels like playing the classic game again, just without needing actual cards.",
  ];

  const fourStarReviews = [
    "Really fun game overall, especially when playing multiplayer with friends and trying to guess the Chor.",
    "The classic Raja Mantri Chor Sipahi concept works really nicely as a mobile game.",
    "Had a pretty good time playing this with friends, especially during the more competitive rounds.",
    "The guessing mechanic is genuinely fun and makes the game much more interesting than expected.",
    "Really enjoyed the multiplayer experience, especially when everyone starts accusing each other randomly.",
    "Simple gameplay but still surprisingly engaging once you start playing with a group of friends.",
    "The game brings back the classic childhood feeling while making everything much easier on mobile.",
    "I liked the role-based gameplay because every round can turn out completely different.",
    "The suspense around finding the Chor is probably my favorite part of the whole game.",
    "Really nice casual game when you want something fun to play with friends.",
    "The rounds are quick and entertaining, so it is easy to keep playing without getting bored.",
    "Had fun trying to figure out who was lying and who actually had the Chor role.",
    "The multiplayer mode definitely makes the game more enjoyable when you have friends playing together.",
    "Really like the basic concept, and the guessing makes it more strategic than it initially looks.",
    "The game is easy to learn, but playing against friends makes it surprisingly competitive.",
    "Enjoyed the classic concept and how naturally it works as a modern mobile game.",
    "The role guessing is pretty addictive because you always want to see if your prediction was right.",
    "Had a good time playing this with friends, especially when everyone started defending themselves.",
    "Really fun game for quick multiplayer sessions when you don't want something too complicated.",
    "The gameplay has a nice mix of guessing and strategy without making things difficult to understand.",
    "I enjoyed the suspense during each round because nobody knows exactly what everyone else is planning.",
    "The classic Chor Police idea is still fun, and this mobile version makes it convenient.",
    "Really liked the multiplayer rounds because every group seems to create completely different situations.",
    "The game is pretty straightforward, but the social guessing makes it much more entertaining.",
    "Had more fun than expected, especially after playing a few rounds with friends.",
    "The hidden roles make every round interesting because you have to actually pay attention.",
    "Really enjoyed trying different strategies instead of simply guessing randomly every time.",
    "This is a nice casual game that works especially well when several friends are playing together.",
    "The gameplay is simple but still creates some seriously funny moments during multiplayer.",
    "I like how quickly the rounds move because there is not much unnecessary waiting.",
    "The guessing part keeps the game interesting, especially when someone manages to completely fool everyone.",
    "Really fun concept and definitely better when you have a few friends joining the same game.",
    "The game captures the old-school Chor Police feeling while giving it a convenient mobile setup.",
    "Enjoyed playing this because every round feels slightly different depending on everyone's decisions.",
    "The multiplayer experience is pretty solid and makes the game much more enjoyable with friends.",
    "I liked the combination of hidden roles and guessing because it keeps everyone involved.",
    "Really entertaining game for casual sessions, especially when you want something competitive with friends.",
    "The rounds are short, so it is easy to play several matches without feeling tired.",
    "Had a good experience overall, especially during the rounds where everyone started blaming each other.",
    "The concept is simple but surprisingly fun once you start thinking about everyone's possible roles.",
    "Really enjoyed the guessing and suspense, although I definitely got fooled a few times.",
    "This game is pretty fun with friends because the accusations and guesses make things interesting.",
    "The classic game translates nicely to mobile, and the gameplay is easy to pick up.",
    "I enjoyed the role-based system because it gives each round a different kind of challenge.",
    "Really nice game for quick matches, especially when you have friends around to play with.",
    "The gameplay is casual but still gives you enough strategy to keep thinking during rounds.",
    "Had fun playing this and trying to predict who would actually turn out to be Chor.",
    "The multiplayer aspect adds much more excitement compared with simply playing the game alone.",
    "Overall really enjoyable, especially if you already know Raja Mantri Chor Sipahi from childhood.",
    "The game has a fun concept, although having even more multiplayer options would make it better.",
    "Really enjoyed the guessing mechanics, especially when playing with friends who take their roles seriously.",
    "The classic gameplay is still enjoyable, and the mobile format makes it easier to play anytime.",
    "Had a good time with the multiplayer mode, especially when everyone started making suspicious choices.",
    "The role system is fun and gives each player something interesting to think about.",
    "Really liked the short rounds because they keep the game moving without becoming repetitive.",
    "The guessing is probably the strongest part because you can never be completely sure about anyone.",
    "Enjoyable game overall, especially for groups looking for something casual but still competitive.",
    "The childhood nostalgia definitely adds something special when playing this version with friends.",
    "Really liked how simple the rules are because new players can understand them pretty quickly.",
    "The multiplayer rounds can get surprisingly intense when everyone starts defending their choices.",
    "Had fun trying to read other players and predict who might secretly be the Chor.",
    "The game is easy to pick up and works nicely for quick sessions with friends.",
    "Really enjoyable concept, although having more variety between rounds could make it even better.",
    "The hidden-role idea keeps things interesting because you never know what another player is planning.",
    "I enjoyed the suspense during the reveals because sometimes the obvious suspect is completely innocent.",
    "The multiplayer experience is definitely more fun when everyone knows the classic game already.",
    "Really good casual game for friends, especially when you want something that does not take forever.",
    "The gameplay is straightforward and entertaining, though I would love even more ways to play.",
    "Had some funny moments playing this because everyone kept accusing the wrong person.",
    "The guessing system makes the game more interesting than I expected from such a simple concept.",
    "Really liked the competitive feeling, especially when trying to beat friends across multiple rounds.",
    "The game does a nice job of keeping everyone involved during the role guessing.",
    "Enjoyed the overall experience, especially the moments when someone successfully hides their Chor role.",
    "The classic concept still works really well, and playing it digitally is definitely convenient.",
    "Really fun with a group, although having more customization would make the experience even better.",
    "The rounds feel quick and easy to replay, which is nice for casual gaming sessions.",
    "I liked the strategy involved in figuring out which players might be hiding something.",
    "The multiplayer mode adds a lot more fun compared with simply playing through individual rounds.",
    "Had a good time playing with friends, especially when everyone's guesses started getting completely random.",
    "The game has a nice balance of simple rules and interesting decisions during each round.",
    "Really enjoyed the nostalgia, although I think additional game modes could make it even more replayable.",
    "The Chor guessing is fun because sometimes you can confidently choose someone and still be wrong.",
    "Overall a pretty enjoyable game, especially when you have friends ready for a few rounds.",
    "The social guessing makes this much more entertaining than I expected when I first opened it.",
    "Really liked the hidden-role mechanics and the suspense before finding out everyone's actual role.",
    "The game is simple enough for casual players while still giving competitive players something to think about.",
    "Had fun playing several rounds because the outcomes kept changing depending on everyone's decisions.",
    "The classic Raja Mantri Chor Sipahi concept is a great fit for quick mobile matches.",
    "Really enjoyed playing with friends, especially when people started changing their strategy after losing.",
    "The gameplay is fun and accessible, although I would like to see even more variety eventually.",
    "The final reveal is always interesting because you never know whether your guess was actually correct.",
    "Good casual multiplayer game with a familiar concept and enough guessing to keep things interesting.",
    "Really liked the competitive atmosphere that develops when everyone starts trying to identify the Chor.",
    "The game is easy to understand and has enough suspense to make the rounds enjoyable.",
    "Had a fun experience overall, especially when playing with friends who already know the classic game.",
    "The hidden roles create some genuinely funny situations when everyone becomes suspicious of each other.",
    "Really enjoyed the guessing aspect, although a few more gameplay variations would be nice.",
    "The multiplayer mode is definitely where most of the fun comes from when playing with friends.",
    "Nice adaptation of the classic game, and the quick rounds make it easy to keep playing.",
    "I enjoyed trying different approaches each round instead of always making the same kind of guess.",
    "The game has a good casual vibe and works especially well for groups of friends.",
    "Really liked the suspense and guessing, although more features could make the experience even deeper.",
    "Overall a fun mobile version of Raja Mantri Chor Sipahi that is especially enjoyable with friends.",
    "The simple rules make it easy to introduce to someone new and start playing quickly.",
    "Had a good time figuring out the roles and seeing whether my guesses were actually correct.",
    "The multiplayer experience is entertaining and gets much better once everyone understands the strategy.",
    "Really enjoyed the classic feeling, and the mobile format makes it much easier to play anywhere.",
    "The gameplay is fun and competitive without requiring complicated controls or a huge time commitment.",
    "I liked how each round can turn out differently depending on who gets which role.",
    "Good experience overall, especially for casual multiplayer sessions where everyone wants something quick and fun.",
    "The guessing mechanics are enjoyable and give the simple concept more depth than expected.",
    "Really liked playing this with friends, especially when everyone started trying to outsmart each other.",
    "The game is fun enough for repeated matches, although more variety would make it even better.",
    "Had a nice time playing and definitely enjoyed the suspense around finding the actual Chor.",
    "The classic concept feels natural on mobile, and the multiplayer guessing keeps things entertaining.",
    "Overall a fun experience with friends, especially when everyone starts taking their guesses seriously.",
  ];

  const pool = rating === 5 ? fiveStarReviews : fourStarReviews;

  return pool[Math.floor(Math.random() * pool.length)];
};
